### ISSUE TITLE
Not trolling but embarrassing 

### ISSUE THREAD

**Issue by oerdnj** [lovenunu/leftpad-c#4]
Sorry but your code is not trolling, but embarrassing. The code is horrible. fprintf can pad with ' ' (and even with generic padding character with a little push) and at least you should use memset and strcpy instead of the for loops.

**Comment by lovenunu** [comment]
As you may saw, I'm not used to work with C at all. The goal was not to provide a production ready snippet, just write something that kinda work to give an answer to a tweet :)
I didn't even know that *printf could do the job !
Anyway, thanks for your issue, i'm gonna take a look at memset and strcpy :)

**Comment by oerdnj** [comment]
Slightly better and you are willing to learn, that's good :)

Those functions are really one liners in C, see: https://gist.github.com/oerdnj/db040b7f489d2ed84e27

Used like this:
```
#include "left_pad.h"
#define SZ 8
int main(void) {
  char buf[SZ+1];
  left_pad_str(buf, SZ, "foo", "XXXXXXXX");
}
```

**Comment by bortzmeyer** [comment]
Or https://gist.github.com/oerdnj/db040b7f489d2ed84e27

**Comment by lovenunu** [comment]
I guess that's why there's no standard implementation ^^ Once again thank you !
